### ISSUE TITLE
Uninstall does not do full cleanup and causes graphical glitch

### ISSUE THREAD

**Issue by nathan-weinberg** [flozz/cover-thumbnailer#13]
After installing and uninstalling cover-thunbnailer, several of the generated files (e.g. `AlbumArtSmall.jpg`) remained after the uninstallation. I removed the files, but I'm now getting some weird graphical glitches with certain folders such as `Music` and some subfolders. Attached a screenshot of what the affected folders look like. Any help to fix this would be appreciated - happy to provide more info.

![image](https://user-images.githubusercontent.com/31703736/184376301-112b164d-a8c3-4df0-8b50-8a71b2a1b5a4.png)

Specs:
- Fedora 36
- GNOME 42.3.1
- GNOME nautilus 42.2

**Comment by flozz** [comment]
I am not sure to understand what your problem is.

If the problem is that folder thumbnails remain after uninstalling Cover Thumbnailer, this is a normal behavior (as Cover Thumbnailer work like any other thumbnailer). To fix this just remove the `~/.cache/thumbnails/`:

    rm -rf ~/.cache/thumbnails/

This will remove all thumbnails (including Cover Thumbnailer's ones), and the other thumbnails (images, videos, documents,...) will be automatically regenerated.

**Comment by nathan-weinberg** [comment]
That fixed it - would you be open to a PR to add this to the uninstall? Either way feel free to close this issue, thanks.

**Comment by flozz** [comment]
When you uninstall other thumbnailers they do not clear the cache. The cache is not managed by the thumbnailer but mainly by file managers (and it is shared between different softwares). 

Also, I think it is hazardous to do that, as we may have to do the same operation for all users of the system, and it will remove all thumbnails, not only the ones generated by Cover Thumbnailer :)
